src/Entity/ScoreUniversity.php
<?php

namespace App\Entity;

use App\Repository\ScoreUniversityRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ScoreUniversityRepository::class)]
class ScoreUniversity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $score = null;

    #[ORM\ManyToOne(inversedBy: 'scoreUniversities')]
    private ?University $university = null;

    #[ORM\ManyToOne(inversedBy: 'scoreUniversities')]
    private ?Filiere $Filiere = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getScore(): ?float
    {
        return $this->score;
    }

    public function setScore(float $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getUniversity(): ?University
    {
        return $this->university;
    }

    public function setUniversity(?University $university): self
    {
        $this->university = $university;

        return $this;
    }

    public function getFiliere(): ?Filiere
    {
        return $this->Filiere;
    }

    public function setFiliere(?Filiere $Filiere): self
    {
        $this->Filiere = $Filiere;

        return $this;
    }
}

src/Entity/University.php
<?php

namespace App\Entity;

use App\Repository\UniversityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UniversityRepository::class)]
class University
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotNull]
    #[ORM\Column(length: 255)]
    private ?string $UniversityName = null;


    #[ORM\ManyToOne(inversedBy: 'universities')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotNull]
    private ?Governorats $ville = null;

    #[ORM\OneToMany(mappedBy: 'university', targetEntity: ScoreUniversity::class)]
    private Collection $scoreUniversities;

    public function __construct()
    {
        $this->scoreUniversities = new ArrayCollection();
    }






    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUniversityName(): ?string
    {
        return $this->UniversityName;
    }

    public function setUniversityName(string $UniversityName): self
    {
        $this->UniversityName = $UniversityName;

        return $this;
    }

    public function getVille(): ?Governorats
    {
        return $this->ville;
    }

    public function setVille(?Governorats $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection<int, ScoreUniversity>
     */
    public function getScoreUniversities(): Collection
    {
        return $this->scoreUniversities;
    }

    public function addScoreUniversity(ScoreUniversity $scoreUniversity): self
    {
        if (!$this->scoreUniversities->contains($scoreUniversity)) {
            $this->scoreUniversities->add($scoreUniversity);
            $scoreUniversity->setUniversity($this);
        }

        return $this;
    }

    public function removeScoreUniversity(ScoreUniversity $scoreUniversity): self
    {
        if ($this->scoreUniversities->removeElement($scoreUniversity)) {
            // set the owning side to null (unless already changed)
            if ($scoreUniversity->getUniversity() === $this) {
                $scoreUniversity->setUniversity(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->UniversityName;
    }


}

src/Form/UniversityType.php
<?php

namespace App\Form;

use App\Entity\Filiere;
use App\Entity\Governorats;
use App\Entity\University;
use App\Repository\FiliereRepository;
use App\Repository\GovernoratsRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UniversityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('UniversityName')
            ->add('ville',EntityType::class,[
                'class'=>Governorats::class,
                'multiple'=>false,
                'expanded'=>false,
                'required'=>true,
                'query_builder' => function (GovernoratsRepository $er) {
                    return $er->createQueryBuilder('S')
                        ->orderBy('S.name', 'ASC');
                },
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => University::class,
        ]);
    }
}

src/Controller/UniversityController.php
<?php

namespace App\Controller;

use App\Entity\University;
use App\Form\UniversityType;
use App\Repository\UniversityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
#[Route("/Dashbord")]
class UniversityController extends AbstractController
{
    #[Route('/university', name: 'List_universitys')]
    public function index(UniversityRepository $repository): Response
    {
        $universitys=$repository->findAll();
        #dd($universitys);
        return $this->render('university/ListUniversity.html.twig', [
            'universitys'=>$universitys
        ]);
    }
    #[Route('/Adduniversity', name: 'Add_universitys')]
    public function adduniversity(UniversityRepository $repository,Request $request): Response
    {
        $university=new University();
        $form=$this->createForm(UniversityType::class,$university);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() ){
            #   dd($university);
            $repository->save($university,true);
            return $this->redirectToRoute("List_universitys");
        }
        return $this->render('university/UniversityForm.html.twig', [
            'form'=>$form->createView(),
            "button"=>"save"
        ]);
    }

    #[Route('/Updateuniversity/{id<\d+>}', name: 'updata_universitys')]
    public function updateuniversity(UniversityRepository $repository,Request $request,University $university): Response
    {
        $form=$this->createForm(UniversityType::class,$university);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() ){
            #   dd($university);
            $repository->save($university,true);
            return $this->redirectToRoute("List_universitys");
        }
        return $this->render('university/UniversityForm.html.twig', [
            'form'=>$form->createView(),
            "button"=>"update"
        ]);
    }

    #[Route('/Deleteuniversity/{id<\d+>}', name: 'delete_universitys')]
    public function deleteuniversity(UniversityRepository $repository,Request $request,University $university): Response
    {

            $repository->remove($university,true);
            return $this->redirectToRoute("List_universitys");


    }
}

templates/university/ListUniversity.html.twig
{% extends 'dashbord_ctrl/DashbordBase.html.twig' %}
{% block MainBody %}
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Universitys list</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">universitys list</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-12">

                        <!-- /.card -->
                        <div class="card">

                            <!-- /.card-header -->
                            <div class="card-body">
                                <a href="{{ path('Add_universitys') }}" class="btn btn-success" ><i class="fa-solid fa-circle-plus"></i> Add University</a>
                                <table id="Datatable1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>id</th>
                                        <th>univesity Name</th>
                                        <th>ville</th>
                                        <th>Specialiter</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for u in universitys %}
                                        <tr>
                                            <td>{{ u.id }}</td>
                                            <td>{{ u.UniversityName }}</td>
                                            <td>{{ u.ville.name }}</td>
                                            <td>
                                                {% for f in u.filiere %}
                                                    <ul>
                                                        <li>{{ f.FiliereName }}</li>
                                                    </ul>
                                                {% endfor %}
                                            </td>
                                            <td>
                                                <a href="{{ path("updata_universitys",{id:u.id}) }}" style="padding: 40px" ><i class="fa-solid fa-pen-to-square"></i></a>
                                                <a href="{{ path("delete_universitys",{id:u.id}) }}" ><i class="fa-solid fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    {% block Scripts %}
        <!-- DataTables  & Plugins -->
        <script src="{{ asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
        <script src=".{{ asset('plugins/jszip/jszip.min.js') }}"></script>
        <script src=".{{ asset('plugins/pdfmake/pdfmake.min.js') }}"></script>
        <script src="{{ asset('plugins/pdfmake/vfs_fonts.js') }}"></script>
        <script src="{{ asset('plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
        <script src="{{ asset('plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
        <script>
            $(function () {
                $("#Datatable1").DataTable({
                    "responsive": true,
                    "lengthChange": false,
                    "autoWidth": false,
                    "searching":true,
                    "info": false,
                }).input().appendTo('#Datatable1_wrapper .col-md-6');
            });
        </script>
    {% endblock %}
{% endblock %}

templates/university/UniversityForm.html.twig
{% extends 'dashbord_ctrl/DashbordBase.html.twig' %}
{% block Syle %}

{% endblock %}
{% block MainBody %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Dashboard</h1>
                    </div><!-- /.col -->

                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <div class="card" style="min-height: 400px;" >
            <!-- /.card-header -->
            <div class="card-body" >
                <!-- Main content -->
                <section class="content" >
                    <div class="container-sm">

                        <!-- Small boxes (Stat box) -->
                        <div class="row justify-content-md-center" >
                            <div class="col-md-8">
                                <div class="container">
                                    {{ form_start(form) }}
                                    <div class="mb-3">
                                        <label for="exampleInputEmail1" class="form-label">university</label>
                                        {{ form_widget(form.UniversityName,{'attr':{'placeholder':'university name',"class":"form-control"}}) }}
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleInputEmail1" class="form-label">ville</label>
                                        {{ form_widget(form.ville,{'attr':{'placeholder':'',"class":"form-control -select2"}}) }}
                                    </div>
                                    <div class="mb-3">
                                        <label for="exampleInputEmail1" class="form-label">Specialiter</label>
                                        {{ form_widget(form.filiere,{'attr':{'placeholder':'Nom Du Specialiter',"class":"form-control -select2"}}) }}
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" value="{{ button }}" class="btn-lg float-right btn-success m-4">
                                    </div>
                                    <div class="form-group">
                                        <a href="{{ path('List_universitys') }}" class="btn-lg float-right btn-secondary m-4" formnovalidate>Cancel </a>
                                    </div>

                                    {{ form_end(form) }}


                                </div>
                            </div>
                        </div>

                    </div><!-- /.container-fluid -->
                </section>
            </div>
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
{% block Scripts %}
    <script>
        $(document).ready(function() {
            $('.-select2').select2({
                placeholder:' '
            });
        });
    </script>
{% endblock %}
{% endblock %}